#!/bin/sh

handle=/usr/local/share/lint

usage() {
cat <<-EOF
$0 <file> 
Run file through error lint, output menu correlating to errors
Selecting a menu entry will open the file, moving the cursor to that error
EOF
	exit 0
}

##main - run handlers based on extension
test -z $1 && usage

pid="`xprop -id $1 | awk '/NET_WM_PID/{print $NF}'`"
set -- "`ps $pid | awk '/edit/{print $9}'`"

case $1 in
	*.go)    set -- "`$handle/go_lint $1`" ;;
	*.c|*.h) set -- "`$handle/c_lint  $1`" ;;
	*)       set -- "`$handle/sh_lint $1`" ;;
esac
varless() {
	printf '%s\n' "$1" | less
}

$TERMINAL -e varless "$@" &
