#!/bin/sh

handle=/usr/local/share/lint

usage() {
cat <<-EOF
$0 <file> 
Run file through error lint, output menu correlating to errors
Selecting a menu entry will open the file, moving the cursor to that error
EOF
	exit 0
}

##main - run handlers based on extension
test -z $1 && usage

case $1 in
	*.go)    $handle/go_lint  $1 ;;
	*.c|*.h) $handle/c_lint   $1 ;;
	*.lua)   $handle/lua_lint $1 ;;
	*)       $handle/sh_lint  $1 ;;
esac

