#!/usr/bin/env bash

clang-check $1 &>/dev/stdout | while read -r line; do
	case "$line" in
		$1*)	num="`cut -d ':' -f2 <<< "$line"`"
			error="`awk '{ $1=""; print }' <<< "$line"`"
			printf 'line: %s error:%s\n' "$num" "$error" ;; 
	esac
done
