#!/usr/bin/env bash

go test $1 &>/dev/stdout | while read -r line; do
	name="$(basename $1)"
	case "$line" in
		*$name*)	num="$(cut -d ':' -f2 <<< "$line")"
				error="$(awk '{ $1=""; print }' <<< "$line")"
				printf 'line: %s error:%s\n' "$num" "$error" ;;
	esac
done
