#!/usr/bin/env bash

lint_bash() {
	bash -D $1 &>/dev/stdout | while read -r line; do
		case "$line" in
			$1*)	num="$(cut -d ':' -f 2 <<< "$line" | awk '{print $2}')"
				error="$(awk '{ $1=""; $2=""; $3=""; print}' <<< "$line")"
				printf 'line:%s error:%s\n' "$num" "${error/  /}" ;;
		esac
	done
}

lint_posix() {
	sh $1 &>/dev/stdout | while read -r line; do
		case "$line" in
		$1*)	num="$(cut -d ':' -f 2 <<< "$line" | sed 's/ $//')"
			error="$(awk '{ $1=""; $2=""; $3=""; print}' <<< "$line")"
			printf 'line:%s error:%s\n' "$num" "$error" ;;
		esac
	done
}

#read #! from first line
case "$(head -n 1 $1)" in
	*bin/bash*|*usr/bin/env\ bash*) lint_bash $1 ;;
	*bin/sh*) lint_posix $1 ;;
esac

