#!/bin/sh
# filter out messages that don't include our client name
# parse line numbers and error string, pretty print
clck() {
	case "`head -n 1 $1`" in
		*bin/bash*|*usr/bin/env\ bash*) bash -D "$1" 2>&1 | grep "^$1" ;;
		*bin/sh*) sh "$1" 2>&1 | grep "^$1" ;;
	esac
}

clck $1 | while read -r line; do
	num="`printf '%s\n' "$line" | cut -d ':' -f 2 | sed 's/line //'`"
	error="`printf '%s\n' "$line" | awk '{ $1=""; $2=""; $3=""; print}'`"
	printf 'line:%s error:%s\n' "$num" "$error"
done
